### ISSUE TITLE
fix bug/misalignment when detecting empty entrypoint error condition

### ISSUE THREAD

**Issue by jbrekelmans** [jbrekelmans/kube-compose#155]
#82 introduced support for the command option in docker-compose services, but it does not deal with the service `asdf` in the following docker-compose service entirely accurately:
```yaml
version: '2.1'
services:
  asdf:
    image: ubuntu:latest
    entrypoint: []
    command: []
```
When running the service `asdf` via docker-compose the container can be created successfully, but kube-compose thinks this is an error. What happens is that the CMD of the image ubuntu:latest is used as the entrypoint. Task is to align behavior.
